spring:
  application:
    name: board
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace