spring:
  application:
    name: board
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/board
    username: sa
    password: 1234
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  servlet:
    multipart:
      enabled: true
      fileSizeThreshold: 0B
      maxFileSize: 1MB
      maxRequestSize: 10MB
cloud:
  aws:
    region:
      static: ap-southeast-2
    stack:
      auto: false
    credentials:
      accessKey:
      secretKey:
    s3:
      bucket: